dist:
  name: custom
  output_path: ./bin

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.140.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.140.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.140.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.140.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/backstageprocessor v0.140.0
    path: .

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.140.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.140.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.140.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.140.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.140.0
